% Function INVOKE-DEBUGGER

[UP](9.2.html)  

---

# Function **INVOKE-DEBUGGER**


Function `INVOKE-DEBUGGER`


## 構文

`invoke-debugger` *condition* => `|`


## 引数と戻り値

*condition* - コンディションオブジェクト


## 定義

[`invoke-debugger`](9.2.invoke-debugger.html)は、*condition*とともにデバッガーへ入ろうと試みます。

もし[`*debugger-hook*`](9.2.debugger-hook.html)が[`nil`](5.3.nil-variable.html)ではないとき、
その値は関数（あるいは関数の名前）で無ければならず、
標準のデバッガーに入る前に呼び出されます。
その関数が呼び出されるときに
[`*debugger-hook*`](9.2.debugger-hook.html)には[`nil`](5.3.nil-variable.html)が束縛され、
その関数は2つの引数として*condition*と、
[`nil`](5.3.nil-variable.html)を束縛する前の
[`*debugger-hook*`](9.2.debugger-hook.html)の値が渡されます。
もしその関数が普通に終わったとき、標準のデバッガーに入ります。

標準のデバッガーは決して直接戻りません。
戻るときは、`restart`関数を使用したような
ただ非局所的な遷移の制御のみで起こります。


## 例文

```lisp
(ignore-errors ;Normally, this would suppress debugger entry
  (handler-bind ((error #'invoke-debugger)) ;But this forces debugger entry
    (error "Foo.")))
Debug: Foo.
To continue, type :CONTINUE followed by an option number:
 1: Return to Lisp Toplevel.
Debug>
```


## 副作用

[`*debugger-hook*`](9.2.debugger-hook.html)は[`nil`](5.3.nil-variable.html)に束縛され、
プログラムの実行は中止となり、
デバッガーに入ります。


## 影響

[`*debug-io*`](21.2.debug-io.html),
[`*debugger-hook*`](9.2.debugger-hook.html),


## 例外

なし。


## 参考

[`error`](9.2.error-function.html),
[`break`](9.2.break.html)


## 備考

なし。


---
[TOP](index.html),  [Github](https://github.com/nptcl/npt-japanese)

